# Install the real NevanCode workspace and expose it as `nevan` on Windows.
# This does NOT wrap the published `codebuff` npm package. It downloads this
# repository, installs Bun dependencies, prepares a local dev/proxy server, and
# creates a launcher that starts Nevan services before opening the Nevan CLI.

$ErrorActionPreference = 'Stop'

$RepoOwner = if ($env:NEVAN_REPO_OWNER) { $env:NEVAN_REPO_OWNER } else { 'nevanai' }
$RepoName = if ($env:NEVAN_REPO_NAME) { $env:NEVAN_REPO_NAME } else { 'NevanCode' }
$RepoBranch = if ($env:NEVAN_REPO_BRANCH) { $env:NEVAN_REPO_BRANCH } else { 'main' }
$NevanHome = if ($env:NEVAN_HOME) { $env:NEVAN_HOME } else { Join-Path $env:USERPROFILE '.nevan' }
$RepoDir = if ($env:NEVAN_REPO_DIR) { $env:NEVAN_REPO_DIR } else { Join-Path $NevanHome $RepoName }
$InstallDir = if ($env:NEVAN_INSTALL_DIR) { $env:NEVAN_INSTALL_DIR } else { Join-Path $env:LOCALAPPDATA 'Nevan\bin' }
$WebPort = if ($env:NEVAN_WEB_PORT) { $env:NEVAN_WEB_PORT } else { '3000' }
$AppUrl = if ($env:NEVAN_APP_URL) { $env:NEVAN_APP_URL } else { "http://localhost:$WebPort" }
$ZipUrl = "https://github.com/$RepoOwner/$RepoName/archive/refs/heads/$RepoBranch.zip"

function Info($Message) { Write-Host "==> $Message" -ForegroundColor Cyan }
function Ok($Message) { Write-Host "✓ $Message" -ForegroundColor Green }
function Warn($Message) { Write-Host "! $Message" -ForegroundColor Yellow }

function Ensure-Bun {
  $bun = Get-Command bun -ErrorAction SilentlyContinue
  if ($bun) { return $bun.Source }

  if ($env:NEVAN_INSTALL_TEST_MODE -eq '1') { return 'bun' }

  Info 'Bun was not found; installing Bun automatically'
  irm https://bun.sh/install.ps1 | iex

  $candidate = Join-Path $env:USERPROFILE '.bun\bin\bun.exe'
  if (Test-Path $candidate) { return $candidate }

  $bun = Get-Command bun -ErrorAction SilentlyContinue
  if ($bun) { return $bun.Source }

  throw 'Bun installation finished, but bun was not found. Reopen PowerShell and run the installer again.'
}

function Install-Repo {
  if ($env:NEVAN_INSTALL_TEST_MODE -eq '1') {
    New-Item -ItemType Directory -Force -Path (Join-Path $RepoDir 'cli\src') | Out-Null
    New-Item -ItemType Directory -Force -Path (Join-Path $RepoDir 'debug\console') | Out-Null
    $packageJson = Join-Path $RepoDir 'package.json'
    if (-not (Test-Path $packageJson)) {
      '{"scripts":{"up":"echo up","down":"echo down","ps":"echo ps"}}' | Set-Content -Path $packageJson -Encoding UTF8
    }
    return
  }

  New-Item -ItemType Directory -Force -Path $NevanHome | Out-Null
  $temp = Join-Path ([System.IO.Path]::GetTempPath()) ("nevancode-" + [System.Guid]::NewGuid().ToString('N'))
  New-Item -ItemType Directory -Force -Path $temp | Out-Null
  try {
    $zipPath = Join-Path $temp 'nevancode.zip'
    Info "Downloading NevanCode from $RepoOwner/$RepoName ($RepoBranch)"
    Invoke-WebRequest -Uri $ZipUrl -OutFile $zipPath
    Expand-Archive -Path $zipPath -DestinationPath $temp -Force
    $extracted = Get-ChildItem -Path $temp -Directory | Where-Object { $_.Name -like "$RepoName-*" } | Select-Object -First 1
    if (-not $extracted) { throw 'Could not find extracted NevanCode directory.' }

    if (Test-Path $RepoDir) { Remove-Item -Path $RepoDir -Recurse -Force }
    New-Item -ItemType Directory -Force -Path $RepoDir | Out-Null
    Copy-Item -Path (Join-Path $extracted.FullName '*') -Destination $RepoDir -Recurse -Force
  } finally {
    Remove-Item -Path $temp -Recurse -Force -ErrorAction SilentlyContinue
  }
}

function Write-DefaultEnv {
  $envFile = Join-Path $RepoDir '.env.local'
  if (Test-Path $envFile) {
    Ok "Keeping existing $envFile"
  } else {
    Info 'Creating local Nevan environment defaults'
  @"
# Auto-generated by scripts/install-nevan.ps1.
# Replace placeholder provider keys with real keys if you want the local server
# to call external LLM/payment/analytics services.
NEXT_PUBLIC_CB_ENVIRONMENT=dev
NEXT_PUBLIC_CODEBUFF_APP_URL=$AppUrl
NEXT_PUBLIC_WEB_PORT=$WebPort
PORT=$WebPort
NEXTAUTH_URL=$AppUrl
NEXTAUTH_SECRET=nevancode-local-development-secret
DATABASE_URL=postgres://manicode_user_local:local_db_password@localhost:5432/manicode_db_local
POSTGRES_USER=manicode_user_local
POSTGRES_PASSWORD=local_db_password
POSTGRES_DB=manicode_db_local

OPEN_ROUTER_API_KEY=placeholder-local-openrouter-key
OPENAI_API_KEY=placeholder-local-openai-key
ANTHROPIC_API_KEY=placeholder-local-anthropic-key
FIREWORKS_API_KEY=placeholder-local-fireworks-key
LINKUP_API_KEY=placeholder-local-linkup-key
GRAVITY_API_KEY=placeholder-local-gravity-key
IPINFO_TOKEN=placeholder-local-ipinfo-token
CODEBUFF_GITHUB_ID=placeholder-local-github-id
CODEBUFF_GITHUB_SECRET=placeholder-local-github-secret
STRIPE_SECRET_KEY=stripe_placeholder_local
STRIPE_WEBHOOK_SECRET_KEY=stripe_webhook_placeholder_local
STRIPE_TEAM_FEE_PRICE_ID=price_placeholder_local
STRIPE_SUBSCRIPTION_100_PRICE_ID=price_placeholder_local_100
STRIPE_SUBSCRIPTION_200_PRICE_ID=price_placeholder_local_200
STRIPE_SUBSCRIPTION_500_PRICE_ID=price_placeholder_local_500
LOOPS_API_KEY=placeholder-local-loops-key
DISCORD_PUBLIC_KEY=placeholder-local-discord-public-key
DISCORD_BOT_TOKEN=placeholder-local-discord-bot-token
DISCORD_APPLICATION_ID=placeholder-local-discord-application-id
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=stripe_publishable_placeholder_local
NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL=$AppUrl/profile
NEXT_PUBLIC_SUPPORT_EMAIL=support@nevancode.local
NEXT_PUBLIC_POSTHOG_API_KEY=posthog_placeholder_local
NEXT_PUBLIC_POSTHOG_HOST_URL=http://localhost:3000
"@ | Set-Content -Path $envFile -Encoding UTF8
  }

  function Ensure-EnvVar($Key, $Value) {
    if (-not (Select-String -Path $envFile -Pattern "^$([regex]::Escape($Key))=" -Quiet)) {
      Add-Content -Path $envFile -Value "$Key=$Value"
    }
  }

  Ensure-EnvVar 'NEXT_PUBLIC_CB_ENVIRONMENT' 'dev'
  Ensure-EnvVar 'NEXT_PUBLIC_CODEBUFF_APP_URL' $AppUrl
  Ensure-EnvVar 'NEXT_PUBLIC_WEB_PORT' $WebPort
  Ensure-EnvVar 'PORT' $WebPort
  Ensure-EnvVar 'NEXTAUTH_URL' $AppUrl
  Ensure-EnvVar 'NEXT_PUBLIC_SUPPORT_EMAIL' 'support@nevancode.local'
  Ensure-EnvVar 'NEXT_PUBLIC_POSTHOG_API_KEY' 'posthog_placeholder_local'
  Ensure-EnvVar 'NEXT_PUBLIC_POSTHOG_HOST_URL' 'http://localhost:3000'
  Ensure-EnvVar 'NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY' 'stripe_publishable_placeholder_local'
  Ensure-EnvVar 'NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL' "$AppUrl/profile"
  Ensure-EnvVar 'POSTGRES_USER' 'manicode_user_local'
  Ensure-EnvVar 'POSTGRES_PASSWORD' 'local_db_password'
  Ensure-EnvVar 'POSTGRES_DB' 'manicode_db_local'
}

function Install-Dependencies($BunPath) {
  if ($env:NEVAN_INSTALL_TEST_MODE -eq '1') {
    Ok 'Test mode: skipped dependency installation'
    return
  }

  Info 'Installing NevanCode dependencies with Bun'
  & $BunPath install --cwd $RepoDir
}

function Test-RequiredDependencies {
  $required = @(
    (Join-Path $RepoDir 'node_modules\react\jsx-dev-runtime.js'),
    (Join-Path $RepoDir 'node_modules\next\package.json'),
    (Join-Path $RepoDir 'node_modules\drizzle-kit\package.json')
  )

  foreach ($path in $required) {
    if (-not (Test-Path $path)) { return $false }
  }
  return $true
}

function Write-Launcher($BunPath) {
  New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

  $psLauncher = Join-Path $InstallDir 'nevan.ps1'
  @"
`$ErrorActionPreference = 'Stop'

`$RepoOwner = '$RepoOwner'
`$RepoName = '$RepoName'
`$RepoBranch = '$RepoBranch'
`$RepoDir = if (`$env:NEVAN_REPO_DIR) { `$env:NEVAN_REPO_DIR } else { '$RepoDir' }
`$BunPath = if (`$env:BUN_BIN) { `$env:BUN_BIN } else { '$BunPath' }
`$WebPort = if (`$env:NEVAN_WEB_PORT) { `$env:NEVAN_WEB_PORT } else { '$WebPort' }
`$AppUrl = if (`$env:NEVAN_APP_URL) { `$env:NEVAN_APP_URL } else { "http://localhost:`$WebPort" }
`$UserCwd = (Get-Location).Path

function Usage {
  Write-Host 'Nevan CLI'
  Write-Host ''
  Write-Host 'Usage:'
  Write-Host '  nevan [prompt/options]       Start Nevan. Services/proxy start automatically.'
  Write-Host '  nevan --setup-only           Start only the background server/proxy stack.'
  Write-Host '  nevan --status               Show Nevan background service status.'
  Write-Host '  nevan --stop                 Stop Nevan background services.'
  Write-Host '  nevan --update               Re-run the installer/update NevanCode.'
}

if (-not (Test-Path `$RepoDir)) {
  Write-Error "NevanCode workspace is missing at: `$RepoDir. Reinstall with: irm https://raw.githubusercontent.com/$RepoOwner/$RepoName/$RepoBranch/scripts/install-nevan.ps1 | iex"
  exit 1
}

if (-not (Test-Path `$BunPath)) {
  `$bun = Get-Command bun -ErrorAction SilentlyContinue
  if (`$bun) { `$BunPath = `$bun.Source } else { throw 'Bun is required. Install it from https://bun.sh/ and run nevan again.' }
}

function Test-Health {
  try {
    `$response = Invoke-WebRequest -Uri "`$AppUrl/api/healthz" -UseBasicParsing -TimeoutSec 3
    return (`$response.StatusCode -ge 200 -and `$response.StatusCode -lt 300)
  } catch { return `$false }
}

function Load-NevanEnv {
  `$envFile = Join-Path `$RepoDir '.env.local'
  if (-not (Test-Path `$envFile)) { `$envFile = Join-Path `$RepoDir '.env' }
  if (Test-Path `$envFile) {
    Get-Content `$envFile | ForEach-Object {
      if (`$_ -and -not `$_.StartsWith('#') -and `$_.Contains('=')) {
        `$parts = `$_.Split('=', 2)
        [Environment]::SetEnvironmentVariable(`$parts[0], `$parts[1], 'Process')
      }
    }
  }
  `$script:AppUrl = if (`$env:NEXT_PUBLIC_CODEBUFF_APP_URL) { `$env:NEXT_PUBLIC_CODEBUFF_APP_URL } else { `$AppUrl }
  `$script:WebPort = if (`$env:NEXT_PUBLIC_WEB_PORT) { `$env:NEXT_PUBLIC_WEB_PORT } else { `$WebPort }
}

function Ensure-NevanDependencies {
  `$required = @(
    (Join-Path `$RepoDir 'node_modules\react\jsx-dev-runtime.js'),
    (Join-Path `$RepoDir 'node_modules\next\package.json'),
    (Join-Path `$RepoDir 'node_modules\drizzle-kit\package.json')
  )

  `$missing = `$false
  foreach (`$path in `$required) {
    if (-not (Test-Path `$path)) { `$missing = `$true; break }
  }

  if (`$missing) {
    Write-Host 'Nevan dependencies are missing or incomplete; repairing with Bun...'
    & `$BunPath install --cwd `$RepoDir --force
    if (`$LASTEXITCODE -ne 0) { exit `$LASTEXITCODE }
  }
}

function Start-NevanServices {
  Load-NevanEnv
  Ensure-NevanDependencies
  if (Test-Health) { return }
  Write-Host "Starting Nevan server/proxy stack in the background on `$AppUrl ..."
  Write-Host "Ports: web/proxy=`$WebPort, postgres=5432, studio=4983"
  `$env:NEXT_PUBLIC_CODEBUFF_APP_URL = `$AppUrl
  `$env:NEXT_PUBLIC_WEB_PORT = `$WebPort
  `$env:PORT = `$WebPort
  & `$BunPath --cwd `$RepoDir up
  if (`$LASTEXITCODE -ne 0) { exit `$LASTEXITCODE }
}

switch (`$args[0]) {
  '--help' { Usage; exit 0 }
  '-h' { Usage; exit 0 }
  '--setup-only' { Start-NevanServices; Write-Host "Nevan server/proxy is ready at `$AppUrl"; exit 0 }
  '--status' { & `$BunPath --cwd `$RepoDir ps; exit `$LASTEXITCODE }
  '--stop' { & `$BunPath --cwd `$RepoDir down; exit `$LASTEXITCODE }
  '--update' { irm "https://raw.githubusercontent.com/$RepoOwner/$RepoName/$RepoBranch/scripts/install-nevan.ps1" | iex; exit `$LASTEXITCODE }
}

Start-NevanServices
Set-Location (Join-Path `$RepoDir 'cli')
Ensure-NevanDependencies
try { & `$BunPath run scripts/prebuild-agents.ts *> `$null } catch {}
& `$BunPath run src/index.tsx --cwd `$UserCwd @args
exit `$LASTEXITCODE
"@ | Set-Content -Path $psLauncher -Encoding UTF8

  $cmdLauncher = Join-Path $InstallDir 'nevan.cmd'
  @"
@echo off
powershell -NoProfile -ExecutionPolicy Bypass -File "$psLauncher" %*
"@ | Set-Content -Path $cmdLauncher -Encoding ASCII
}

Info 'Installing Nevan CLI (not Codebuff wrapper)'
$BunPath = Ensure-Bun
Install-Repo
Write-DefaultEnv
Install-Dependencies -BunPath $BunPath
if ($env:NEVAN_INSTALL_TEST_MODE -ne '1') {
  if (-not (Test-RequiredDependencies)) {
    Warn 'Dependency install appears incomplete; retrying once with --force'
    & $BunPath install --cwd $RepoDir --force
  }
  if (-not (Test-RequiredDependencies)) {
    throw 'NevanCode dependency installation is incomplete. Missing react/jsx-dev-runtime.js, next, or drizzle-kit.'
  }
}
Write-Launcher -BunPath $BunPath

$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
$pathParts = @()
if ($userPath) { $pathParts = $userPath -split ';' }
if ($pathParts -notcontains $InstallDir) {
  $newUserPath = if ($userPath) { "$userPath;$InstallDir" } else { $InstallDir }
  [Environment]::SetEnvironmentVariable('Path', $newUserPath, 'User')
  $env:Path = "$env:Path;$InstallDir"
  Ok "Added to user PATH: $InstallDir"
}

Ok "Nevan command installed at $InstallDir\nevan.cmd"

if ($env:NEVAN_SKIP_AUTO_START -eq '1' -or $env:NEVAN_INSTALL_TEST_MODE -eq '1') {
  Write-Host 'Run: nevan'
} else {
  Info 'Preparing Nevan background server/proxy now'
  try { & (Join-Path $InstallDir 'nevan.cmd') --setup-only } catch { Warn "Auto-start did not finish. Run 'nevan --status' or check $RepoDir\debug\console\*.log." }
  Write-Host 'Run: nevan'
}
