#!/usr/bin/env bash
set -euo pipefail

# Install the real NevanCode workspace and expose it as `nevan`.
# This does NOT wrap the published `codebuff` npm package. It downloads this
# repository, installs Bun dependencies, prepares a local dev/proxy server, and
# creates a launcher that starts Nevan services before opening the Nevan CLI.

REPO_OWNER="${NEVAN_REPO_OWNER:-nevanai}"
REPO_NAME="${NEVAN_REPO_NAME:-NevanCode}"
REPO_BRANCH="${NEVAN_REPO_BRANCH:-main}"
NEVAN_HOME="${NEVAN_HOME:-$HOME/.nevan}"
REPO_DIR="$NEVAN_HOME/$REPO_NAME"
INSTALL_DIR="${NEVAN_INSTALL_DIR:-$HOME/.local/bin}"
WEB_PORT="${NEVAN_WEB_PORT:-3000}"
APP_URL="${NEVAN_APP_URL:-http://localhost:$WEB_PORT}"
TARBALL_URL="https://github.com/$REPO_OWNER/$REPO_NAME/archive/refs/heads/$REPO_BRANCH.tar.gz"

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

info() {
  printf '\033[1;34m==>\033[0m %s\n' "$1"
}

ok() {
  printf '\033[1;32m✓\033[0m %s\n' "$1"
}

warn() {
  printf '\033[1;33m!\033[0m %s\n' "$1"
}

fail() {
  printf '\033[1;31m✗\033[0m %s\n' "$1" >&2
}

ensure_bun() {
  if command_exists bun; then
    BUN_BIN="$(command -v bun)"
    return 0
  fi

  if [ "${NEVAN_INSTALL_TEST_MODE:-}" = "1" ]; then
    BUN_BIN="bun"
    return 0
  fi

  if ! command_exists curl; then
    fail "curl is required to install Bun automatically. Install Bun manually from https://bun.sh/ then re-run this installer."
    exit 1
  fi

  info "Bun was not found; installing Bun automatically"
  curl -fsSL https://bun.sh/install | bash

  if [ -x "$HOME/.bun/bin/bun" ]; then
    BUN_BIN="$HOME/.bun/bin/bun"
  elif command_exists bun; then
    BUN_BIN="$(command -v bun)"
  else
    fail "Bun installation finished, but bun was not found. Add ~/.bun/bin to PATH and re-run."
    exit 1
  fi
}

install_repo() {
  if [ "${NEVAN_INSTALL_TEST_MODE:-}" = "1" ]; then
    mkdir -p "$REPO_DIR/cli/src" "$REPO_DIR/debug/console"
    [ -f "$REPO_DIR/package.json" ] || printf '{"scripts":{"up":"echo up","down":"echo down","ps":"echo ps"}}\n' > "$REPO_DIR/package.json"
    return 0
  fi

  if ! command_exists curl; then
    fail "curl is required to download NevanCode."
    exit 1
  fi
  if ! command_exists tar; then
    fail "tar is required to extract NevanCode."
    exit 1
  fi

  mkdir -p "$NEVAN_HOME"
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "$TMP_DIR"' EXIT

  info "Downloading NevanCode from $REPO_OWNER/$REPO_NAME ($REPO_BRANCH)"
  curl -fL "$TARBALL_URL" -o "$TMP_DIR/nevancode.tar.gz"
  tar -xzf "$TMP_DIR/nevancode.tar.gz" -C "$TMP_DIR"

  rm -rf "$REPO_DIR"
  mkdir -p "$REPO_DIR"
  # The extracted folder is normally NevanCode-main. Copy its contents only.
  EXTRACTED_DIR="$(find "$TMP_DIR" -maxdepth 1 -type d -name "$REPO_NAME-*" | head -n 1)"
  if [ -z "$EXTRACTED_DIR" ]; then
    fail "Could not find extracted NevanCode directory."
    exit 1
  fi
  cp -R "$EXTRACTED_DIR"/. "$REPO_DIR"/
}

write_default_env() {
  mkdir -p "$REPO_DIR"
  ENV_FILE="$REPO_DIR/.env.local"

  if [ -f "$ENV_FILE" ]; then
    ok "Keeping existing $ENV_FILE"
  else
    info "Creating local Nevan environment defaults"
    cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/install-nevan.sh.
# Replace placeholder provider keys with real keys if you want the local server
# to call external LLM/payment/analytics services.
NEXT_PUBLIC_CB_ENVIRONMENT=dev
NEXT_PUBLIC_CODEBUFF_APP_URL=$APP_URL
NEXT_PUBLIC_WEB_PORT=$WEB_PORT
PORT=$WEB_PORT
NEXTAUTH_URL=$APP_URL
NEXTAUTH_SECRET=nevancode-local-development-secret
DATABASE_URL=postgres://manicode_user_local:local_db_password@localhost:5432/manicode_db_local
POSTGRES_USER=manicode_user_local
POSTGRES_PASSWORD=local_db_password
POSTGRES_DB=manicode_db_local

OPEN_ROUTER_API_KEY=placeholder-local-openrouter-key
OPENAI_API_KEY=placeholder-local-openai-key
ANTHROPIC_API_KEY=placeholder-local-anthropic-key
FIREWORKS_API_KEY=placeholder-local-fireworks-key
LINKUP_API_KEY=placeholder-local-linkup-key
GRAVITY_API_KEY=placeholder-local-gravity-key
IPINFO_TOKEN=placeholder-local-ipinfo-token
CODEBUFF_GITHUB_ID=placeholder-local-github-id
CODEBUFF_GITHUB_SECRET=placeholder-local-github-secret
STRIPE_SECRET_KEY=stripe_placeholder_local
STRIPE_WEBHOOK_SECRET_KEY=stripe_webhook_placeholder_local
STRIPE_TEAM_FEE_PRICE_ID=price_placeholder_local
STRIPE_SUBSCRIPTION_100_PRICE_ID=price_placeholder_local_100
STRIPE_SUBSCRIPTION_200_PRICE_ID=price_placeholder_local_200
STRIPE_SUBSCRIPTION_500_PRICE_ID=price_placeholder_local_500
LOOPS_API_KEY=placeholder-local-loops-key
DISCORD_PUBLIC_KEY=placeholder-local-discord-public-key
DISCORD_BOT_TOKEN=placeholder-local-discord-bot-token
DISCORD_APPLICATION_ID=placeholder-local-discord-application-id
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=stripe_publishable_placeholder_local
NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL=$APP_URL/profile
NEXT_PUBLIC_SUPPORT_EMAIL=support@nevancode.local
NEXT_PUBLIC_POSTHOG_API_KEY=posthog_placeholder_local
NEXT_PUBLIC_POSTHOG_HOST_URL=http://localhost:3000
EOF
  fi

  ensure_env_var() {
    key="$1"
    value="$2"
    if ! grep -q "^${key}=" "$ENV_FILE"; then
      printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    fi
  }

  ensure_env_var NEXT_PUBLIC_CB_ENVIRONMENT dev
  ensure_env_var NEXT_PUBLIC_CODEBUFF_APP_URL "$APP_URL"
  ensure_env_var NEXT_PUBLIC_WEB_PORT "$WEB_PORT"
  ensure_env_var PORT "$WEB_PORT"
  ensure_env_var NEXTAUTH_URL "$APP_URL"
  ensure_env_var NEXT_PUBLIC_SUPPORT_EMAIL support@nevancode.local
  ensure_env_var NEXT_PUBLIC_POSTHOG_API_KEY posthog_placeholder_local
  ensure_env_var NEXT_PUBLIC_POSTHOG_HOST_URL http://localhost:3000
  ensure_env_var NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY stripe_publishable_placeholder_local
  ensure_env_var NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL "$APP_URL/profile"
  ensure_env_var POSTGRES_USER manicode_user_local
  ensure_env_var POSTGRES_PASSWORD local_db_password
  ensure_env_var POSTGRES_DB manicode_db_local
  return 0
}


install_dependencies() {
  if [ "${NEVAN_INSTALL_TEST_MODE:-}" = "1" ]; then
    ok "Test mode: skipped dependency installation"
    return 0
  fi

  info "Installing NevanCode dependencies with Bun"
  "$BUN_BIN" install --cwd "$REPO_DIR"
}

test_required_dependencies() {
  [ -f "$REPO_DIR/node_modules/react/jsx-dev-runtime.js" ] && \
    [ -f "$REPO_DIR/node_modules/next/package.json" ] && \
    [ -f "$REPO_DIR/node_modules/drizzle-kit/package.json" ]
}

write_launcher() {
  mkdir -p "$INSTALL_DIR"

  cat > "$INSTALL_DIR/nevan" <<EOF
#!/usr/bin/env bash
set -euo pipefail

NEVAN_HOME="\${NEVAN_HOME:-$NEVAN_HOME}"
REPO_DIR="\${NEVAN_REPO_DIR:-$REPO_DIR}"
BUN_BIN="\${BUN_BIN:-$BUN_BIN}"
WEB_PORT="\${NEVAN_WEB_PORT:-$WEB_PORT}"
APP_URL="\${NEVAN_APP_URL:-http://localhost:\$WEB_PORT}"
USER_CWD="\$(pwd)"

command_exists() { command -v "\$1" >/dev/null 2>&1; }

usage() {
  cat <<'USAGE'
Nevan CLI

Usage:
  nevan [prompt/options]       Start Nevan. Services/proxy start automatically.
  nevan --setup-only           Start only the background server/proxy stack.
  nevan --status               Show Nevan background service status.
  nevan --stop                 Stop Nevan background services.
  nevan --update               Re-run the installer/update NevanCode.
USAGE
}

if [ ! -d "\$REPO_DIR" ]; then
  echo "NevanCode workspace is missing at: \$REPO_DIR" >&2
  echo "Reinstall with:" >&2
  echo "  curl -fsSL https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/$REPO_BRANCH/scripts/install-nevan.sh | bash" >&2
  exit 1
fi

if [ ! -x "\$BUN_BIN" ] && ! command_exists "\$BUN_BIN"; then
  if command_exists bun; then
    BUN_BIN="\$(command -v bun)"
  elif [ -x "\$HOME/.bun/bin/bun" ]; then
    BUN_BIN="\$HOME/.bun/bin/bun"
  else
    echo "Bun is required. Install it from https://bun.sh/ and run nevan again." >&2
    exit 1
  fi
fi

is_healthy() {
  if command_exists curl; then
    curl -fsS "\$APP_URL/api/healthz" >/dev/null 2>&1
  else
    return 1
  fi
}

load_nevan_env() {
  if [ -f "\$REPO_DIR/.env.local" ]; then
    set -a
    # shellcheck disable=SC1091
    . "\$REPO_DIR/.env.local"
    set +a
  elif [ -f "\$REPO_DIR/.env" ]; then
    set -a
    # shellcheck disable=SC1091
    . "\$REPO_DIR/.env"
    set +a
  fi
  APP_URL="\${NEXT_PUBLIC_CODEBUFF_APP_URL:-\$APP_URL}"
  WEB_PORT="\${NEXT_PUBLIC_WEB_PORT:-\$WEB_PORT}"
}

ensure_nevan_dependencies() {
  if [ ! -f "\$REPO_DIR/node_modules/react/jsx-dev-runtime.js" ] || \
     [ ! -f "\$REPO_DIR/node_modules/next/package.json" ] || \
     [ ! -f "\$REPO_DIR/node_modules/drizzle-kit/package.json" ]; then
    echo "Nevan dependencies are missing or incomplete; repairing with Bun..."
    "\$BUN_BIN" install --cwd "\$REPO_DIR" --force
  fi
}

start_services() {
  load_nevan_env
  ensure_nevan_dependencies
  if is_healthy; then
    return 0
  fi

  echo "Starting Nevan server/proxy stack in the background on \$APP_URL ..."
  echo "Ports: web/proxy=\$WEB_PORT, postgres=5432, studio=4983"
  export NEXT_PUBLIC_CODEBUFF_APP_URL="\$APP_URL"
  export NEXT_PUBLIC_WEB_PORT="\$WEB_PORT"
  export PORT="\$WEB_PORT"
  "\$BUN_BIN" --cwd "\$REPO_DIR" up
}

case "\${1:-}" in
  --help|-h)
    usage
    exit 0
    ;;
  --setup-only)
    start_services
    echo "Nevan server/proxy is ready at \$APP_URL"
    exit 0
    ;;
  --status)
    exec "\$BUN_BIN" --cwd "\$REPO_DIR" ps
    ;;
  --stop)
    exec "\$BUN_BIN" --cwd "\$REPO_DIR" down
    ;;
  --update)
    exec bash -c "\$(curl -fsSL https://raw.githubusercontent.com/$REPO_OWNER/$REPO_NAME/$REPO_BRANCH/scripts/install-nevan.sh)"
    ;;
 esac

start_services || exit $?
cd "\$REPO_DIR/cli"
ensure_nevan_dependencies
"\$BUN_BIN" run scripts/prebuild-agents.ts >/dev/null 2>&1 || true
exec "\$BUN_BIN" run src/index.tsx --cwd "\$USER_CWD" "\$@"
EOF

  chmod +x "$INSTALL_DIR/nevan"
}

main() {
  info "Installing Nevan CLI (not Codebuff wrapper)"
  ensure_bun
  install_repo
  write_default_env
  install_dependencies
  if [ "${NEVAN_INSTALL_TEST_MODE:-}" != "1" ]; then
    if ! test_required_dependencies; then
      warn "Dependency install appears incomplete; retrying once with --force"
      "$BUN_BIN" install --cwd "$REPO_DIR" --force
    fi
    if ! test_required_dependencies; then
      fail "NevanCode dependency installation is incomplete. Missing react/jsx-dev-runtime.js, next, or drizzle-kit."
      exit 1
    fi
  fi
  write_launcher

  ok "Nevan command installed at $INSTALL_DIR/nevan"

  case ":$PATH:" in
    *":$INSTALL_DIR:"*) ;;
    *)
      warn "Add this directory to PATH if 'nevan' is not found: $INSTALL_DIR"
      ;;
  esac

  if [ "${NEVAN_SKIP_AUTO_START:-}" = "1" ] || [ "${NEVAN_INSTALL_TEST_MODE:-}" = "1" ]; then
    echo "Run: nevan"
  else
    info "Preparing Nevan background server/proxy now"
    "$INSTALL_DIR/nevan" --setup-only || warn "Auto-start did not finish. Run 'nevan --status' or check $REPO_DIR/debug/console/*.log."
    echo "Run: nevan"
  fi
}

main "$@"
